knpu_oauth2_client:
    clients:
        keycloak:
            type: keycloak
            auth_server_url: '%env(KEYCLOAK_URL)%'
            client_id: '%env(KEYCLOAK_CLIENT_ID)%'
            client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'
            realm: '%env(KEYCLOAK_REALM)%'
            redirect_route: admin_auth_callback
            redirect_params: {}
