name: Deploy service

on:
  push:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: https://mediatekformation.vinceh121.me
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          cd /var/www/html/cned/mediatekformation
          git pull
          composer i
          bin/console doctrine:m:m
