name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup MariaDB
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "mariadb-10.11"
    - run: mysql -uroot -e 'CREATE DATABASE mediatekformation_test;'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run database migrations
      run: ./bin/console d:m:m
    - name: Load data fixtures
      run: yes | ./bin/console d:f:l
    - name: Run test suite
      run: ./bin/phpunit
